### ISSUE TITLE
When using matcher with ctrlp suggestion list only appears when hitting backspace

### ISSUE THREAD

**Issue by EDmitry** [burke/matcher#14]
I am not sure wether this is ctrlP issue or matcher's but I only see the suggestion list when I press the backspace for the first time. Then suggestion list populates and works.
Where may be a problem?
Thanks.

**Comment by burke** [comment]
I've heard a few people tell me about this recently. I haven't changed matcher in ages, so presumably it's a behaviour change in Ctrl-P. @fw42, you were getting this, right? Did you find a fix?

**Comment by fw42** [comment]
Yepp same thing, no fix :-( But I only started using CtrlP a few days ago, so I might be using a more up-to-date version than you, Burke.

**Comment by burke** [comment]
Fixed on master, I believe. Thanks, @mleech!

Reopen if it's still broken.
