### ISSUE TITLE
Version number, for package managers

### ISSUE THREAD

**Issue by kballenegger** [burke/matcher#19]
Making an official release would make it possible to release this tool on package managers. Specifically, I tried to make a Homebrew formula for this, but was (sensibly) rejected because I just made up an unofficial version number.

See https://github.com/Homebrew/homebrew/pull/35012#issuecomment-67068393

**Comment by burke** [comment]
Sure, no problem!
- https://github.com/burke/matcher/commit/6c54c265dbcd89e0058a385fd42c3a84349f4ae6
- https://github.com/burke/matcher/releases/tag/1.0.0
